@startuml

class MotADeviner {
  - array ListeMot
  - string LeMotsADevine
  - int LongueurMot
  - array TableauUnderscoreMot
  + __construct()
  + getMot() : string
  + getMotCache() : array
  + updateMotCache(string $lettre) : void
  + isComplete() : bool
}

class JeuPendu {
  - MotADeviner Mot
  - int Nb_erreur
  - array lettreProposer
  + __construct()
  + jouer() : void
  + afficherMotCache() : void
  + demanderLettre() : string
  + traiterLettre(string $lettre) : void

  }

MotADeviner <|-- JeuPendu

@enduml
